# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector:
  type: "epsilon_greedy"
  epsilon_start: 1.0
  epsilon_finish: 0.05
  epsilon_anneal_time: 50000

macro_action_selector:
  type: "epsilon_greedy"
  epsilon_start: 1.0
  epsilon_finish: 0.05
  epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "haven_learner"
double_q: True
mixer: "qmix"
macro_mixer: "graphmix"
value_mixer: "qmix"
name: "group"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

n_subgoals: 14 #不同场景不一致 2s3z:11 3s_5z :11 8m:14 MMM2: 18 27m_vs_30m:36  5m_vs_6m:12 8m_vs_9m:15 2c_vs_64zg:70,70  训练时候需要把这行中文删掉
k: 3 #3 27m_vs_30m:12 MMM2:3

macro_mac: "separate_mac"
mean_weight: True
intrinsic_switch: 1
reward_switch: 1

agent: "macro"
agent_macro: "latent_ce_dis_rnn"

lambda_local: 1

latent_dim: 3 #3 27m_vs_30m:12 MMM2:3
kl_loss_weight: 0.0001
h_loss_weight: 0.0001
var_floor: 0.002
NN_HIDDEN_SIZE: 16
dis_loss_weight: 0.001
dis_time: 0
soft_constraint_weight: 1.0
roma_raw: False


dis_sigmoid: False